reverse_complement: Parallelize processing within each sequence
TeXitoi/benchmarksgame-rs pull request #46
Opened 2017-02-27 00:26 UTC by mbrubeck

Rather than process each sequence on one thread, this processes each sequence on `n` threads where `n` is the number of CPU cores. This improves CPU utilization, and reduces running time on `input25000000.txt` by 2–3% on my 4-core desktop.

2017-02-27 08:38 UTC, TeXitoi commented on src/reverse_complement.rs
> +    let jhs = iter.map(|(a, b)| {
`parallel` is really not idiomatic. It was written when scoped_spawn was discovered unsound. Now, we can write that safely using crossbeam. 

But maybe a rayon approach is more appropriate?

2017-02-27 17:27 UTC, mbrubeck commented
> `parallel` is really not idiomatic. It was written when scoped_spawn was discovered unsound. Now, we can write that safely using crossbeam.
> 
> But maybe a rayon approach is more appropriate?

Sure, I'll try both.  I also found that I can get another 2% or so by parallelizing the newline code, but I need to fix some bugs in my approach before submitting that.

2017-02-27 17:47 UTC, mbrubeck commented
I ended up restoring the parallelism across sequences.  This means that at times there may be more threads running than ideal, but it is a win anyway.  All together, this version now runs on `input25000000.txt` in 6% less time than the version on master.

This was my other attempt to parallelize newline handling, but it was a net loss, probably due to overhead from the number of threads spawned and joined: https://github.com/mbrubeck/benchmarksgame-rs/commit/475b6a5f54defdb1198c907573a438d4421ed82b

It might be faster to get better CPU utilization without the overhead by using a thread pool with a work-stealing queue, but that would be a bigger change and I'm not sure whether it would actually translate into better overall speed.

2017-02-27 22:52 UTC, TeXitoi commented on src/reverse_complement.rs
> +extern crate libc;
If libc is only for memchr, maybe the safe and rustic version https://crates.io/crates/memchr can be used.

2017-02-27 23:31 UTC, TeXitoi commented on src/reverse_complement.rs
> +        });
Can't we rewrite a lot of that without unsafe, limiting unsafe to the `&mut [u16]` creations?

2017-02-27 23:37 UTC, TeXitoi commented
Great work!

2017-02-28 04:35 UTC, mbrubeck commented
> If libc is only for memchr, maybe the safe and rustic version https://crates.io/crates/memchr can be used.

Done.

> Can't we rewrite a lot of that without unsafe, limiting unsafe to the `&mut [u16]` creations?

Done. This change makes the program slower, but the slowdown is less than 1% on my 4-core desktop.

By the way, I've been doing most of my testing with Rust 1.15 stable, but I also tried these commits with Rust 1.17 nightly.  When compiled with nightly, the latest version runs about 2% faster than when compiled with stable. Also, it seems to eliminate the gap between this version and the one with unsafe pointers.

2017-02-28 08:59 UTC, TeXitoi requested changes
Great!

2017-02-28 08:59 UTC, TeXitoi commented on src/reverse_complement.rs
> +                }
Did you tried something like `for (x, y) in left.iter_mut().rev().zip(&mut right)`?

2017-02-28 08:59 UTC, TeXitoi commented on src/reverse_complement.rs
> +        _ => unreachable!()
You forgot the 0 case.

2017-02-28 08:59 UTC, TeXitoi commented on src/reverse_complement.rs
> +    let mut stdin = File::open("/dev/stdin").expect("Could not open /dev/stdin");
:+1:

2017-02-28 09:04 UTC, TeXitoi commented
No idea for your parallel version of the new line shifting.

Having 2xnum_cpus threads is no problem IMHO. That's just a small constant.

2017-02-28 16:18 UTC, mbrubeck commented on src/reverse_complement.rs
> +        _ => unreachable!()
> You forgot the 0 case.

Fixed.

2017-02-28 16:19 UTC, mbrubeck commented on src/reverse_complement.rs
> +                }
> Did you tried something like `for (x, y) in left.iter_mut().rev().zip(&mut right)`?

I tried that earlier and thought it slowed down the code, but I think I messed up the measurements. Tried it again and it works fine.

2017-02-28 16:22 UTC, TeXitoi commented on src/reverse_complement.rs
> +	0 => {}
bad indent

2017-02-28 16:22 UTC, TeXitoi approved these changes

2017-02-28 16:27 UTC, mbrubeck commented on src/reverse_complement.rs
> +	0 => {}
Fixed.

2017-02-28 16:30 UTC, mbrubeck commented
I also experimented with a version that combines the newline processing and the "reverse complement" into a single pass, but I haven't managed to make it competitive with the current version:

https://github.com/mbrubeck/benchmarksgame-rs/blob/reverse_complement_bytes/src/reverse_complement.rs

2017-02-28 16:43 UTC, merged

2017-02-28 16:44 UTC, TeXitoi commented
updated https://alioth.debian.org/tracker/index.php?func=detail&aid=315633&group_id=100815&atid=413122

2017-02-28 16:48 UTC, TeXitoi commented
And thanks again for the great work!